export const ClientPage = {
  textLocators: {
    createClientButton: 'Create Client',
    saveClientButton: 'Save Client',
    updateClientButton: 'Update Client',
    editClientButton: 'Edit Client',
    deleteClientButton: 'Delete Client',
    clientNameLabel: 'Client Name',
    addressLabel: 'Address',
    phoneNumberLabel: 'Phone Number',
    emailLabel: 'Email',
    timezoneLabel: 'Timezone',
    maxDraftsLabel: 'Max Drafts',
    legalStatementLabel: 'Legal Statement',
    createClientTitle: 'Create Client',
    editClientTitle: 'Edit Client',
    clientCreatedSuccessMsg: 'Client has been created successfully.',
    clientUpdatedSuccessMsg: 'Client has been saved successfully.',
    clientDeletedSuccessMsg: 'Client has been deleted successfully.',
    clientNameRequired: 'Client name is required',
    addressRequired: 'Address is required',
    deleteConfirmationMsg: 'Are you sure you want to delete this client?',
    deleteButton: 'Delete',
    cancelButton: 'Cancel'
  },
  cssLocators: {
    createClientBtn: '[data-testid="create-client-button"]',
    saveClientBtn: '[data-testid="save-client-button"]',
    updateClientBtn: '[data-testid="update-client-button"]',
    editClientBtn: '[data-testid="edit-client-button"]',
    deleteClientBtn: '[data-testid="delete-client-button"]',
    clientNameInput: 'input[name="clientName"]',
    addressInput: 'input[name="address"]',
    phoneInput: 'input[name="phoneNumber"]',
    emailInput: 'input[name="email"]',
    timezoneDropdown: 'div[data-placeholder="true"]',
    maxDraftsInput: 'input[name="maxDrafts"]',
    legalStatementInput: 'textarea[name="legalStatement"]',
    clientSearchInput: 'input[placeholder*="Search"]',
    clientEditIcon: '.list-edit-icon',
    clientDeleteIcon: '.list-delete-icon'
  },
  xpathLocators: {
    createClientButton: '//button[text()="Create Client"]',
    saveClientButton: '//button[text()="Save Client"]',
    updateClientButton: '//button[text()="Update Client"]',
    editClientButton: '//button[text()="Edit Client"]',
    deleteClientButton: '//button[text()="Delete Client"]',
    clientNameInput: '//input[@name="clientName"]',
    addressInput: '//input[@name="address"]',
    phoneInput: '//input[@name="phoneNumber"]',
    emailInput: '//input[@name="email"]',
    timezoneDropdown: '//span[contains(text(), "Timezone")]/following::div[@data-placeholder="true"]',
    maxDraftsInput: '//input[@name="maxDrafts"]',
    legalStatementInput: '//textarea[@name="legalStatement"]',
    clientCreatedSuccessMsg: '//div[contains(text(), "Client has been created successfully.")]',
    clientUpdatedSuccessMsg: '//div[contains(text(), "Client has been saved successfully.")]',
    clientDeletedSuccessMsg: '//div[contains(text(), "Client has been deleted successfully.")]',
    clientInList: (clientName: string) => `//td[contains(text(), "${clientName}")]`,
    clientEditIcon: (clientName: string) => `//td[contains(text(), "${clientName}")]/following-sibling::td//div[contains(@class, "list-edit-icon")]`,
    clientDeleteIcon: (clientName: string) => `//td[contains(text(), "${clientName}")]/following-sibling::td//div[contains(@class, "list-delete-icon")]`,
    clientSearchInput: '//input[contains(@placeholder, "Search")]',
    validationError: (errorText: string) => `//div[contains(text(), "${errorText}")]`,
    deleteConfirmationDialog: '//div[contains(text(), "Are you sure you want to delete this client?")]',
    deleteConfirmButton: '//button[text()="Delete"]',
    deleteCancelButton: '//button[text()="Cancel"]'
  },
  idLocators: {
    
  },
  titleLocator: {
    
  },
};
